stages:
  - build
  - test

build:
  stage: build
  script:
    - cd tickieSystem
    - ls
    - ./gradlew assemble

test:
  stage: test
  script:
    - cd ReactApp/
    - npm install
    - npm test
  

after_script:
  - echo "End CI"




