stages:
  - build
  - test
  - sonarqube

buildBackEnd:
  stage: build
  script:
    - cd tickieSystem
    - ls
    - ./gradlew assemble

buildMessegingBackEnd:
  stage: build
  script:
    - cd MessagingApp/messaging
    - ls
    - mvn assemble

buildFrontEnd:
  stage: build
  script:
    - cd ReactApp/

testBackEnd:
  stage: test
  script:
    - cd tickieSystem
    - ./gradlew check

testFrontEnd:
  stage: test
  script:
    - cd ReactApp/
    - npm install
    - npm test

sonarqube:
   stage: sonarqube
   script:
    - cd tickieSystem
    - ./gradlew sonarqube

  

after_script:
  - echo "End CI"




