stages:
  - buildBackEnd
  - buildFrontEnd
  - testBackEnd
  - testFrontEnd
  - sonarqube

buildBackEnd:
  stage: buildBackEnd
  script:
    - cd tickieSystem
    - ls
    - ./gradlew assemble

buildFrontEnd:
  stage: buildFrontEnd
  script:
    - cd ReactApp/

testBackEnd:
  stage: testBackEnd
  script:
    - cd tickieSystem

testFrontEnd:
  stage: testFrontEnd
  script:
    - cd ReactApp/
    - npm install
    - npm test

sonarqube:
   stage: sonarqube
   script:
    - cd tickieSystem
    - ./gradlew sonarqube

  

after_script:
  - echo "End CI"




