stages:
  - build
  - test
  - sonarQube

build:
  stage: build
  script:
    - cd tickieSystem
    - ls
    - ./gradlew assemble

test:
  stage: test
  script:
    - cd ReactApp/
    - npm install
    - npm test

sonarQube:
  stage: sonarQube
  script:
    - cd tickieSystem
    - ./gradlew sonarqube    

after_script:
  - echo "End CI"




